#########################
# +-------------------+ #
# | SoulCraft Friends | #
# +-------------------+ #
#########################

# Main Configuration section
friends:

  # This sets how the plugin will handle. By default, any command
  # of the plugin (excluding the RELOAD command) will not activate,
  # but rather open the GUI menu. You can disable this and allow
  # commands to activate without the need of the GUI. This DOES NOT
  # deactivate the GUI, just adds the commands to be usage instead
  # of a forced into GUI usage.
  gui override: true
  
  # Sets the time limit of the gifts. Should the receiver
  # not claim the given gift within the given time, then the
  # item will return to the owners. To remove time limit, put
  # 'none' as the time limit.
  gift time limit: '12H'
  
  # When a person fails to collect the gift in time, this
  # sets the time limit of the original owner to re-claim
  # the item they gifted. Shold they fail within the time
  # limit, then the item moves to the Storage Container.
  # To remove the time limit, put 'none'.
  collect time limit: '12H'
  
  # This puts forth the time in which an item will be stored
  # within the Admin Stroage Container.
  storage time limit: '7D'
  
  # Sets forth a list of items that cannot be sent as a gift.
  # This list does not need to be used, to remove the list
  # either empty the list or comment out the list section.
  # item values are set by their Enumeration name. Visit
  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
  # for a list of names of items.
  #blacklisted items:
  #  - BEDROCK
  #  - SPONGE


# This handles the format for items sent as gifts, items
# returned, and items that are in the ADMIN storage
gui:
  
  # Should the given formats be displayed above the item lore,
  # or below? TRUE sets the format above, FALSE, sets to below.
  display above: true
  
  # Determines if the GUI system will fill any empty spots with
  # the given item below.
  fill empty:
    use: false
    item: GRAY_STAINED_GLASS_PANE
    name: ' '
    amount: 1
    enchanted: false
    lore:
      - ' '
     
   # Creates a border of the given item within the GUI menu. Note
   # that this and the above setting cannot both be used at the
   # same time. If both are active, then this option will override
   # and take affect first.
   fill border:
     use: true
     item: GRAY_STAINED_GLASS_PANE
     name: ' '
     amount: 1
     enchanted: false
     lore:
       - ' '
  
  # This sets how the time will be displayed in the formats.
  # There are two options available, if an input is given that
  # is not one of the two options, then this will default to
  # the 'DHMS' format.
  # 'DHMS' -> '7D 3H 21M 59S'
  # '0000' -> '07:03:21:59'
  time format: 'DHMS'
  
  # The message that will be put into the lore on the item
  # when it is in gift form. This is the message that will
  # appear during the gift interval.
  format gift:
    - '&cSender: &f%sender%'
    - '&cTime Left: &f%time%'
    - '&a&lLeft-Click&f to accept'
    - '&4&lRight-Click to decline'
    - '&6---------------------'
  
  # This displays in the lore of the item when the item
  # has been returned to the owner of the gift.
  format return:
    - '&cGift: &fNot Accepted'
    - '&cTime Left: &f%time%'
    - '&aClick to collect'
    - '&6---------------------'
  
  # Sets the display information of the item found within
  # the Admin Storage.
  format storage:
    - '&cSender: &f%sender%'
    - '&cReceiver: &f%receiver%'
    - '&cTime Left: &f%time%'
    - '&aLeft-Click: &fReturn to Owner'
    - '&dRight-Click: &fTake Item'
    - '&4Middle-Click: &fDelete Item'
    
  # Sets the information of friends within the friend
  # GUI menu.
  # %status% -> Displays either Online (green) or Offline (red)
  # %balance% -> Displays players account balance
  # %date% -> Display when both players became friends
  format friend:
    - '&6Status: %status%'
    - '&76Balance: &a$%balance%'
    - '&6Friends Since: &a%date%'
  
# End Transmission...