#########################
# +-------------------+ #
# | SoulCraft Friends | #
# +-------------------+ #
#########################

# Main Configuration section
friends:
  
  # Sets the time limit of the gifts. Should the receiver
  # not claim the given gift within the given time, then the
  # item will return to the owners. To remove time limit, put
  # 'none' as the time limit.
  # Accepted  Times are D, H and M
  # Apply a space in-between times (7D 23H 17M)
  gift time limit: '12H'
  
  # When a person fails to collect the gift in time, this
  # sets the time limit of the original owner to re-claim
  # the item they gifted. Shold they fail within the time
  # limit, then the item moves to the Storage Container.
  # To remove the time limit, put 'none'.
  # Accepted  Times are D, H and M
  # Apply a space in-between times (7D 23H 17M)
  collect time limit: '12H'
  
  # This puts forth the time in which an item will be stored
  # within the Admin Stroage Container. To remove the time
  # limit, put 'none' as the time limit.
  # Accepted  Times are D, H and M
  # Apply a space in-between times (7D 23H 17M)
  storage time limit: '7D'
  
  # Sets forth a list of items that cannot be sent as a gift.
  # This list does not need to be used, to remove the list
  # either empty the list or comment out the list section.
  # item values are set by their Enumeration name. Visit
  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
  # for a list of names of items.
  #blacklisted items:
  #  - BEDROCK
  #  - SPONGE
  
  # Sets the message that will be sent when the given person
  # does not have permission to perform the action or command
  no permission: '&e&lPERMS &8» &cSorry, you are lacking in the Permission Department to perform that action.'



# End Transmission...