name: SCSettings
main: com.soulcraft.SCSettings
version: 1.0
authors: [Sommod]
description: A Friend system for survival-based servers.

commands:
  survival:
    usage: '§cError, use §b/survival help §cfor a list of commands.'
    description: 'Opens a GUI menu displaying all your friends!'
    aliases: [surv, s]
    

permissions:
  scsettings.*:
    default: op
    description: 'Access to all Commands and Permissions'
    children:
      scsettings.use: true
      scsettings.settings: true
      scsettings.ignorechat: true
      scsettings.override: true
      scsettings.storage: true
      
  scsettings.use:
    default: true
    description: 'Allows having and accessing the Friends System'
    
  scsettings.ignorechat:
    default: op
    description: 'Allows ignoring the normal Chat System'
    
  scsettings.settings:
    default: op
    description: 'Allows editing and changing certain attributes of yourself'
    
  scsettings.override:
    default: op
    description: 'Allows overriding anyones ignore chat command.'
    
  scsettings.storage:
    default: op
    description: 'Allows access to the Admin Storage'