name: SCSettings
main: com.soulcraft.SCSettings
version: 1.1
api-version: 1.16
authors: [Sommod]
depend: [Vault]
description: A Friend system for survival-based servers.

commands:
  scsettings:
    usage: '§cError, use §b/scsettings help §cfor a list of commands.'
    description: 'Opens a GUI menu displaying all your friends!'
    aliases: [survival, surv, s]
    

permissions:
  scsettings.*:
    default: op
    description: 'Access to all Commands and Permissions'
    children:
      scsettings.use: true
      scsettings.allowrequests: true
      scsettings.friendjoin: true
      scsettings.deathmessages: true
      scsettings.ignorechat: true
      scsettings.override: true
      scsettings.storage: true
      scsettings.reload: true
      
  scsettings.use:
    default: true
    description: 'Allows having and accessing the Friends System'
    
  scsettings.ignorechat:
    default: op
    description: 'Allows ignoring the normal Chat System'
    
  scsettings.allowrequests:
    default: op
    description: 'Allows editing and changing the ability to receive friend requests.'
    
  scsettings.friendjoin:
    default: op
    description: 'Can toggle the ability to see when a friend joins the server'
    
  scsettings.deathmessages:
    default: op
    description: 'Toggles seeing Death Messages.'
    
  scsettings.override:
    default: op
    description: 'Allows overriding anyones ignore chat command.'
    
  scsettings.storage:
    default: op
    description: 'Allows access to the Admin Storage'
  
  scsettings.reload:
    default: op
    description: 'Allows reload the plugin and the data within.'